version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ramgee_db
      MYSQL_USER: ramgee
      MYSQL_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "6603:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
